# Setup OpenClaw for AI Event Planner (MiniMax + optional OpenRouter)
# Usage: .\scripts\setup-openclaw.ps1

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

function Resolve-NodeToolchain {
    $candidates = @(
        "C:\Program Files\nodejs",
        "${env:ProgramFiles(x86)}\nodejs",
        "$env:LOCALAPPDATA\Programs\nodejs"
    )
    foreach ($dir in $candidates) {
        if (Test-Path "$dir\npx.cmd") {
            $env:Path = "$dir;" + $env:Path
            return @{
                NodeDir = $dir
                NpxCmd  = "$dir\npx.cmd"
                NpmCmd  = "$dir\npm.cmd"
            }
        }
    }
    $node = Get-Command node -ErrorAction SilentlyContinue
    $npx = Get-Command npx -ErrorAction SilentlyContinue
    if ($node -and $npx) {
        return @{
            NodeDir = Split-Path $node.Source -Parent
            NpxCmd  = $npx.Source
            NpmCmd  = (Get-Command npm -ErrorAction SilentlyContinue).Source
        }
    }
    return $null
}

function Import-DotEnvLine {
    param([string]$Line)
    if ($Line -match '^\s*([^#][^=]+)=(.*)$') {
        $name = $matches[1].Trim()
        $value = $matches[2].Trim()
        Set-Item -Path "env:$name" -Value $value
        return @{ Name = $name; Value = $value }
    }
    return $null
}

function Read-EnvFile {
    param([string]$Path)
    $vars = @{}
    if (-not (Test-Path $Path)) { return $vars }
    Get-Content $Path | ForEach-Object {
        $entry = Import-DotEnvLine $_
        if ($entry) { $vars[$entry.Name] = $entry.Value }
    }
    return $vars
}

function Test-ApiKey {
    param(
        [string]$Key,
        [string[]]$Placeholders = @()
    )
    if (-not $Key) { return $false }
    if ($Key.Length -lt 10) { return $false }
    foreach ($placeholder in $Placeholders) {
        if ($Key -eq $placeholder) { return $false }
    }
    return $true
}

function Write-OpenClawEnvFile {
    param(
        [string]$Path,
        [hashtable]$Vars
    )
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $lines = @(
        "# Auto-generated by scripts/setup-openclaw.ps1",
        "# Gateway reads these vars when started via start-gateway.ps1"
    )
    foreach ($key in ($Vars.Keys | Sort-Object)) {
        $lines += "$key=$($Vars[$key])"
    }
    Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Invoke-OpenClawOnboard {
    param(
        [string]$AuthChoice,
        [hashtable]$ExtraArgs = @{},
        [string]$GatewayPort,
        [string]$Workspace
    )
    $args = @(
        "openclaw", "onboard",
        "--non-interactive",
        "--accept-risk",
        "--mode", "local",
        "--auth-choice", $AuthChoice,
        "--workspace", $Workspace,
        "--gateway-port", $GatewayPort,
        "--gateway-auth", "token",
        "--skip-channels",
        "--no-install-daemon",
        "--skip-search",
        "--skip-health"
    )
    foreach ($key in $ExtraArgs.Keys) {
        $args += $key
        $args += $ExtraArgs[$key]
    }
    & $script:NpxCmd @args
}

Write-Host "=== AI Event Planner: OpenClaw setup ===" -ForegroundColor Cyan

$toolchain = Resolve-NodeToolchain
if (-not $toolchain) {
    Write-Host "Node.js not found. Install: winget install OpenJS.NodeJS.LTS" -ForegroundColor Red
    Write-Host "Then close and reopen PowerShell, or run scripts again." -ForegroundColor Yellow
    exit 1
}
$script:NpxCmd = $toolchain.NpxCmd
$script:NpmCmd = $toolchain.NpmCmd
Write-Host "Using Node.js from $($toolchain.NodeDir)" -ForegroundColor DarkGray

if (-not (Test-Path "node_modules\openclaw")) {
    Write-Host "Installing npm dependencies..." -ForegroundColor Yellow
    & $script:NpmCmd install
}

if (-not (Test-Path ".env")) {
    Write-Host ".env not found. Copy .env.example to .env and add API keys." -ForegroundColor Red
    exit 1
}

$envVars = Read-EnvFile ".env"
$gatewayPort = if ($envVars["OPENCLAW_GATEWAY_PORT"]) { $envVars["OPENCLAW_GATEWAY_PORT"] } else { "18789" }
$openClawEnvPath = Join-Path $env:USERPROFILE ".openclaw\.env"
$gatewayEnv = @{}

$openRouterKey = $envVars["OPENROUTER_API_KEY"]
$openRouterModel = if ($envVars["OPENROUTER_MODEL"]) { $envVars["OPENROUTER_MODEL"] } else { "openrouter/auto" }
$hasOpenRouter = Test-ApiKey -Key $openRouterKey -Placeholders @("your_openrouter_api_key_here")

$codingPlanKey = $envVars["MINIMAX_CODE_PLAN_KEY"]
$oauthToken = $envVars["MINIMAX_OAUTH_TOKEN"]
$minimaxApiKey = $envVars["MINIMAX_API_KEY"]
if (-not $codingPlanKey) {
    if ($minimaxApiKey -and $minimaxApiKey.StartsWith("sk-cp-")) { $codingPlanKey = $minimaxApiKey }
    elseif ($oauthToken -and $oauthToken.StartsWith("sk-cp-")) { $codingPlanKey = $oauthToken }
}
if (-not $oauthToken -and $codingPlanKey) { $oauthToken = $codingPlanKey }
$hasMinimax = Test-ApiKey -Key $codingPlanKey -Placeholders @("your_sk_cp_key_here")

if (-not $hasOpenRouter -and -not $hasMinimax) {
    Write-Host "Add at least one key to .env:" -ForegroundColor Red
    Write-Host "  OPENROUTER_API_KEY=sk-or-...  (https://openrouter.ai/keys)" -ForegroundColor Yellow
    Write-Host "  or MINIMAX_CODE_PLAN_KEY=sk-cp-..." -ForegroundColor Yellow
    exit 1
}

if ($hasOpenRouter) {
    Write-Host "Configuring OpenRouter ($openRouterModel)..." -ForegroundColor Green
    $gatewayEnv["OPENROUTER_API_KEY"] = $openRouterKey
    Invoke-OpenClawOnboard -AuthChoice "openrouter-api-key" -GatewayPort $gatewayPort -Workspace $ProjectRoot -ExtraArgs @{
        "--openrouter-api-key" = $openRouterKey
    }
    & $script:NpxCmd openclaw models set $openRouterModel
}

if ($hasMinimax) {
    Write-Host "Configuring MiniMax Coding Plan (sk-cp-...)..." -ForegroundColor Green
    $gatewayEnv["MINIMAX_CODE_PLAN_KEY"] = $codingPlanKey
    $gatewayEnv["MINIMAX_OAUTH_TOKEN"] = $oauthToken

    if (-not $hasOpenRouter) {
        Invoke-OpenClawOnboard -AuthChoice "minimax-global-api" -GatewayPort $gatewayPort -Workspace $ProjectRoot -ExtraArgs @{
            "--minimax-api-key" = $codingPlanKey
        }
        & $script:NpxCmd openclaw models set minimax-portal/MiniMax-M3
    } else {
        Invoke-OpenClawOnboard -AuthChoice "minimax-global-api" -GatewayPort $gatewayPort -Workspace $ProjectRoot -ExtraArgs @{
            "--minimax-api-key" = $codingPlanKey
        } | Out-Null
        & $script:NpxCmd openclaw models fallbacks clear 2>$null
        & $script:NpxCmd openclaw models fallbacks add minimax-portal/MiniMax-M3
        Write-Host "MiniMax added as fallback when OpenRouter fails." -ForegroundColor Yellow
    }

    $openClawConfigPath = Join-Path $env:USERPROFILE ".openclaw\openclaw.json"
    if (Test-Path $openClawConfigPath) {
        $configText = Get-Content $openClawConfigPath -Raw
        $fixedText = $configText -replace 'https://api\.minimax\.io/anthropic/v1', 'https://api.minimax.io/anthropic'
        if ($fixedText -ne $configText) {
            Set-Content $openClawConfigPath -Value $fixedText -Encoding UTF8 -NoNewline
        }
    }

    $authProfilesPath = Join-Path $env:USERPROFILE ".openclaw\agents\main\agent\auth-profiles.json"
    if (Test-Path (Split-Path $authProfilesPath -Parent)) {
        $authProfilesJson = @{
            version  = 1
            profiles = @{
                "minimax:global" = @{
                    type     = "api_key"
                    provider = "minimax"
                    key      = $codingPlanKey
                }
                "minimax-portal:default" = @{
                    type     = "oauth"
                    provider = "minimax-portal"
                    access   = $codingPlanKey
                    refresh  = ""
                    expires  = 4102444800000
                }
            }
        }
        if ($hasOpenRouter) {
            $authProfilesJson.profiles["openrouter:default"] = @{
                type     = "api_key"
                provider = "openrouter"
                key      = $openRouterKey
            }
        }
        $authProfilesJson | ConvertTo-Json -Depth 10 | Set-Content $authProfilesPath -Encoding UTF8
    }
} elseif ($hasOpenRouter) {
    $authProfilesPath = Join-Path $env:USERPROFILE ".openclaw\agents\main\agent\auth-profiles.json"
    if (Test-Path (Split-Path $authProfilesPath -Parent)) {
        @{
            version  = 1
            profiles = @{
                "openrouter:default" = @{
                    type     = "api_key"
                    provider = "openrouter"
                    key      = $openRouterKey
                }
            }
        } | ConvertTo-Json -Depth 10 | Set-Content $authProfilesPath -Encoding UTF8
    }
}

Write-OpenClawEnvFile -Path $openClawEnvPath -Vars $gatewayEnv

Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Green
if ($hasOpenRouter) {
    Write-Host "Primary model: $openRouterModel"
}
if ($hasMinimax -and $hasOpenRouter) {
    Write-Host "Fallback:      minimax-portal/MiniMax-M3"
} elseif ($hasMinimax) {
    Write-Host "Primary model: minimax-portal/MiniMax-M3"
}
Write-Host "Start gateway:  .\scripts\start-gateway.ps1"
Write-Host "Open dashboard: .\scripts\start-dashboard.ps1"
Write-Host "Check status:   .\scripts\start-gateway.ps1  (then) openclaw models status"
